name: "[Infra] Azure Resources via Terraform"
run-name: "INFRA Azure Resources [${{ inputs.ENVIRONMENT }}]"

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        required: true
        type: choice
        description: "Environment"
        options:
          - develop
          - uat
          - prod

permissions:
  id-token: write
  contents: read
  issues: write

env:
  ARM_TENANT_ID: ${{ vars[format('{0}_AZ_TENANT_ID', inputs.ENVIRONMENT)] }}
  ARM_CLIENT_ID: ${{ vars[format('{0}_AZ_CLIENT_ID', inputs.ENVIRONMENT)] }}
  ARM_SUBSCRIPTION_ID: ${{ vars[format('{0}_AZ_SUBSCRIPTION_ID', inputs.ENVIRONMENT)] }}

jobs:
  terraform:
    concurrency: ${{ github.workflow }}
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout '${{ github.ref_name }}'
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github/actions
          terraform

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ vars[format('{0}_AZ_CLIENT_ID', inputs.ENVIRONMENT)] }}
        tenant-id: ${{ vars[format('{0}_AZ_TENANT_ID', inputs.ENVIRONMENT)] }}
        subscription-id: ${{ vars[format('{0}_AZ_SUBSCRIPTION_ID', inputs.ENVIRONMENT)] }}

    - name: Terraform Init
      uses: zingdevlimited/actions-helpers/azure/terraform-init@v3
      with:
        AZ_CLIENT_ID: ${{ vars[format('{0}_AZ_CLIENT_ID', inputs.ENVIRONMENT)] }}
        AZ_TENANT_ID: ${{ vars[format('{0}_AZ_TENANT_ID', inputs.ENVIRONMENT)] }}
        AZ_SUBSCRIPTION_ID: ${{ vars[format('{0}_AZ_SUBSCRIPTION_ID', inputs.ENVIRONMENT)] }}
        STORAGE_ACCOUNT_RESOURCEGROUP: ${{ vars[format('{0}_STORAGE_ACCOUNT_RESOURCEGROUP', inputs.ENVIRONMENT)] }}
        STORAGE_ACCOUNT_NAME: ${{ vars[format('{0}_STORAGE_ACCOUNT_NAME', inputs.ENVIRONMENT)] }}
        STORAGE_ACCOUNT_CONTAINER: ${{ vars[format('{0}_STORAGE_ACCOUNT_CONTAINER', inputs.ENVIRONMENT)] }}
        TERRAFORM_DIRECTORY: terraform/

    - name: Terraform Plan
      id: plan
      working-directory: terraform/
      run: |
        planOutput=$(terraform plan\
          -detailed-exitcode\
          -input=false\
          -no-color\
          -out=TerraformPlan.txt) || resultCode=$?
        echo "$planOutput"

        if [ -z "$resultCode" ]; then
          echo "::notice::No changes detected from terraform plan."
          echo "CHANGES_DETECTED=false" >> "$GITHUB_OUTPUT"
          exit 0
        elif [ "$resultCode" == "1" ]; then
          exit 1
        fi

        echo "CHANGES_DETECTED=true" >> "$GITHUB_OUTPUT"
        planOutput=$(echo "$planOutput" | grep -v "Refreshing state")

        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "PLAN_OUTPUT<<$EOF" >> "$GITHUB_OUTPUT"
        echo "$planOutput" >> "$GITHUB_OUTPUT"
        echo "$EOF" >> "$GITHUB_OUTPUT"
      env:
        TF_VAR_resource_group: ${{ vars[format('{0}_RESOURCE_GROUP', inputs.ENVIRONMENT)] }}
        TF_VAR_environment: ${{ inputs.ENVIRONMENT }}
        TF_VAR_plan_sku: ${{ vars[format('{0}_PLAN_SKU', inputs.ENVIRONMENT)] }}

    - name: Terraform Apply
      if: steps.plan.outputs.CHANGES_DETECTED == 'true'
      working-directory: terraform/
      run: terraform apply -auto-approve TerraformPlan.txt
